apiVersion: v1
kind: Service
metadata:
  name: traefik-ingress-service
  namespace: kube-system
  annotations:
    external-dns.alpha.kubernetes.io/hostname: test-kubernetes.{{ environ('PUBLIC_DNS_ZONE') }}
  labels:
    k8s-app: traefik-ingress-lb
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    k8s-app: traefik-ingress-lb
  ports:
    - protocol: TCP
      port: 80
      name: web
    - protocol: TCP
      port: 8080
      name: admin
    - protocol: TCP
      port: 443
      name: web-secure
    - protocol: TCP
      port: 8082
      name: metrics
    